#!/bin/sh -e

if [ $# -lt 2 ]; then
    cat << EOM

Usage: $0 image-file fs_type [slice]

Examples:
	
    Mount a CD/DVD image:
    
    mount_image FreeBSD-13.1-RELEASE-amd64-disc1.iso cd9660
    
    Mount a FreeDOS USB image, with the filesystem on slice one (/dev/md0s1):
    
    mount_image FreeBSD-13.1-RELEASE-amd64-memstick.img msdosfs 1
    
    Mount a FreeDOS floppy disk image with the filesystem on the raw volume
    (no partitions/slices):
    
    mount_image FreeBSD-13.1.img msdosfs

    Mount a UDF ISO image:
    
    mount_image FreeBSD-13.1-RELEASE-amd64-disc1.iso udf

EOM
    exit 1
fi

image=$1
fs_type=$2
if [ $# = 3 ]; then
    slice="s$3"
else
    slice=""
fi

# Create directory if it doesn't exist
if [ ! -d "/mnt/diskimage" ]; then
    mkdir -p /mnt/diskimage
fi

# Create memory disk from image
md=`mdconfig -f $image`

if [ ! -f $image ]; then
    printf "$0: Error: $image: No such file.\n"
    exit 1
fi

if ! mount -t $fs_type /dev/$md$slice /mnt/diskimage; then
    devnum=`echo $md | cut -c 3-`
    mdconfig -d -u $devnum
fi

cat << EOM
Be sure to unmount using umount /mnt/diskimage, or the memory disk
will not be detached.
EOM
