#!/bin/sh -e

dir="/mnt/diskimage"
flags="-f"

if ! umount $flags $dir; then
    printf "\nError: failed to unmount $dir\n"
    exit 1
fi

dev=`mount | awk -v dir="$dir" '$3 == dir { print $1 }'`
vol=${dev%s*}
devnum=${vol#/dev/md}

mdconfig -d -u $devnum


